spring.application.name=beluo
spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}
server.address=0.0.0.0

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true

server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# URL
app.frontend-url=${APP_FRONTEND_URL}

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}?retryWrites=true&w=majority
spring.data.mongodb.database=${MONGO_DATABASE}

# OpenAI API Key
openai.api.key=${OPENAI_API_KEY}

# JWT
jwt.secret=${JWT_SECRET}
jwt.access.token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh.token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# Redirect URL
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# Debug
logging.level.org.springframework.security=DEBUG

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email