# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/beluo_test
spring.data.mongodb.database=beluo_test

# monitoring
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always